// src/views/product/SpuPage.vue
<template>
  <el-card>
    <template #header>
      <div class="header-row">
        <span class="title">商品 SPU</span>
        <el-button type="primary" @click="goCreate">新增</el-button>
      </div>
    </template>

    <div class="tab-row">
      <el-space>
        <el-button :type="tabType === PRODUCT_SPU_TAB.FOR_SALE ? 'primary' : 'default'" @click="switchTab(PRODUCT_SPU_TAB.FOR_SALE)">
          出售中({{ counts?.enableCount ?? 0 }})
        </el-button>
        <el-button :type="tabType === PRODUCT_SPU_TAB.IN_WAREHOUSE ? 'primary' : 'default'" @click="switchTab(PRODUCT_SPU_TAB.IN_WAREHOUSE)">
          仓库中({{ counts?.disableCount ?? 0 }})
        </el-button>
        <el-button :type="tabType === PRODUCT_SPU_TAB.SOLD_OUT ? 'primary' : 'default'" @click="switchTab(PRODUCT_SPU_TAB.SOLD_OUT)">
          已售罄({{ counts?.soldOutCount ?? 0 }})
        </el-button>
        <el-button :type="tabType === PRODUCT_SPU_TAB.ALERT_STOCK ? 'primary' : 'default'" @click="switchTab(PRODUCT_SPU_TAB.ALERT_STOCK)">
          警戒库存({{ counts?.alertStockCount ?? 0 }})
        </el-button>
        <el-button :type="tabType === PRODUCT_SPU_TAB.RECYCLE_BIN ? 'primary' : 'default'" @click="switchTab(PRODUCT_SPU_TAB.RECYCLE_BIN)">
          回收站({{ counts?.recycleCount ?? 0 }})
        </el-button>
      </el-space>
    </div>

    <el-form :inline="true" class="filter-row">
      <el-form-item label="商品名称">
        <el-input v-model="name" clearable placeholder="输入商品名称" @keyup.enter="onSearch" />
      </el-form-item>
      <el-form-item label="分类">
        <el-select v-model="categoryId" clearable placeholder="全部分类" style="width: 180px">
          <el-option v-for="item in categories" :key="item.id" :label="item.name" :value="item.id" />
        </el-select>
      </el-form-item>
      <el-form-item label="品牌">
        <el-select v-model="brandId" clearable placeholder="全部品牌" style="width: 180px">
          <el-option v-for="item in brands" :key="item.id" :label="item.name" :value="item.id" />
        </el-select>
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="onSearch">查询</el-button>
        <el-button @click="onReset">重置</el-button>
      </el-form-item>
    </el-form>

    <el-table :data="items" v-loading="loading" border>
      <el-table-column prop="id" label="ID" width="90" />
      <el-table-column label="商品" min-width="240">
        <template #default="scope">
          <div class="product-cell">
            <el-image :src="scope.row.picUrl" fit="cover" style="width: 40px; height: 40px; border-radius: 6px" />
            <span>{{ scope.row.name }}</span>
          </div>
        </template>
      </el-table-column>
      <el-table-column label="分类" width="120">
        <template #default="scope">{{ categoryNameMap[scope.row.categoryId] || scope.row.categoryId }}</template>
      </el-table-column>
      <el-table-column label="品牌" width="120">
        <template #default="scope">{{ brandNameMap[scope.row.brandId] || scope.row.brandId }}</template>
      </el-table-column>
      <el-table-column label="价格" width="110">
        <template #default="scope">¥ {{ fenToYuan(scope.row.price) }}</template>
      </el-table-column>
      <el-table-column prop="salesCount" label="销量" width="90" />
      <el-table-column prop="stock" label="库存" width="90" />
      <el-table-column label="状态" width="100">
        <template #default="scope">
          <el-tag :type="scope.row.status === PRODUCT_SPU_STATUS.ENABLE ? 'success' : scope.row.status === PRODUCT_SPU_STATUS.RECYCLE ? 'info' : 'warning'">
            {{ getProductSpuStatusLabel(scope.row.status) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column label="创建时间" width="180">
        <template #default="scope">{{ formatTime(scope.row.createTime) }}</template>
      </el-table-column>
      <el-table-column label="操作" width="280" fixed="right">
        <template #default="scope">
          <el-space>
            <el-button link @click="goDetail(scope.row.id)">详情</el-button>
            <el-button link type="primary" @click="goEdit(scope.row.id)">修改</el-button>
            <el-button
              v-if="tabType === PRODUCT_SPU_TAB.RECYCLE_BIN"
              link
              @click="onSwitchStatus(scope.row.id, PRODUCT_SPU_STATUS.DISABLE)"
            >
              恢复
            </el-button>
            <el-button v-else link @click="onSwitchStatus(scope.row.id, PRODUCT_SPU_STATUS.RECYCLE)">回收</el-button>
            <el-button
              v-if="scope.row.status !== PRODUCT_SPU_STATUS.RECYCLE"
              link
              @click="onSwitchStatus(scope.row.id, scope.row.status === PRODUCT_SPU_STATUS.ENABLE ? PRODUCT_SPU_STATUS.DISABLE : PRODUCT_SPU_STATUS.ENABLE)"
            >
              {{ scope.row.status === PRODUCT_SPU_STATUS.ENABLE ? '下架' : '上架' }}
            </el-button>
            <el-button v-if="tabType === PRODUCT_SPU_TAB.RECYCLE_BIN" link type="danger" @click="onDelete(scope.row.id)">
              删除
            </el-button>
          </el-space>
        </template>
      </el-table-column>
    </el-table>

    <div class="pager-row">
      <el-pagination
        v-model:current-page="pageNum"
        v-model:page-size="pageSize"
        background
        layout="total, sizes, prev, pager, next"
        :total="total"
        :page-sizes="[10, 20, 50]"
        @current-change="loadData"
        @size-change="onPageSizeChange"
      />
    </div>
  </el-card>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import {
  deleteSpu,
  getBrandSimpleList,
  getCategoryList,
  getSpuCount,
  getSpuPage,
  type BrandResp,
  type CategoryResp,
  type SpuCountResp,
  type SpuResp,
  updateSpuStatus
} from '../../api/admin';
import { PRODUCT_SPU_STATUS, PRODUCT_SPU_TAB, getProductSpuStatusLabel, fenToYuan } from '../../constants/productSpu';

const router = useRouter();
const route = useRoute();
const categoryIdFromQuery = Number(route.query.categoryId || 0) || undefined;

const loading = ref(false);
const brands = ref<BrandResp[]>([]);
const categories = ref<CategoryResp[]>([]);
const counts = ref<SpuCountResp>();

const items = ref<SpuResp[]>([]);
const total = ref(0);
const pageNum = ref(1);
const pageSize = ref(10);
const tabType = ref<number>(PRODUCT_SPU_TAB.FOR_SALE);
const name = ref('');
const categoryId = ref<number | undefined>(categoryIdFromQuery);
const brandId = ref<number | undefined>();

const categoryNameMap = computed<Record<number, string>>(() =>
  Object.fromEntries(categories.value.map((item) => [item.id, item.name]))
);
const brandNameMap = computed<Record<number, string>>(() =>
  Object.fromEntries(brands.value.map((item) => [item.id, item.name]))
);

function formatTime(value?: number) {
  if (!value) {
    return '-';
  }
  return new Date(value).toLocaleString();
}

async function loadMeta() {
  const [brandList, categoryList, countResp] = await Promise.all([getBrandSimpleList(), getCategoryList(), getSpuCount()]);
  brands.value = brandList;
  categories.value = categoryList;
  counts.value = countResp;
}

async function loadData() {
  loading.value = true;
  try {
    const page = await getSpuPage(pageNum.value, pageSize.value, {
      name: name.value.trim() || undefined,
      tabType: tabType.value,
      categoryId: categoryId.value,
      brandId: brandId.value
    });
    items.value = page.list || [];
    total.value = page.total || 0;
  } catch (error) {
    ElMessage.error((error as Error).message);
  } finally {
    loading.value = false;
  }
}

function onSearch() {
  pageNum.value = 1;
  void loadData();
}

function onReset() {
  name.value = '';
  categoryId.value = categoryIdFromQuery;
  brandId.value = undefined;
  pageNum.value = 1;
  void loadData();
}

function switchTab(nextTab: number) {
  tabType.value = nextTab;
  pageNum.value = 1;
  void loadData();
}

function onPageSizeChange() {
  pageNum.value = 1;
  void loadData();
}

function goCreate() {
  void router.push('/product/spu/create');
}

function goDetail(id: number) {
  void router.push(`/product/spu/${id}`);
}

function goEdit(id: number) {
  void router.push(`/product/spu/${id}/edit`);
}

async function onSwitchStatus(id: number, status: number) {
  try {
    await updateSpuStatus(id, status);
    ElMessage.success('状态已更新');
    await Promise.all([loadData(), loadMeta()]);
  } catch (error) {
    ElMessage.error((error as Error).message);
  }
}

async function onDelete(id: number) {
  try {
    await ElMessageBox.confirm(`确认删除 SPU #${id} 吗？`, '确认删除', {
      type: 'warning',
      confirmButtonText: '删除',
      cancelButtonText: '取消'
    });
    await deleteSpu(id);
    ElMessage.success('删除成功');
    await Promise.all([loadData(), loadMeta()]);
  } catch (_error) {
    // ignore cancel
  }
}

onMounted(async () => {
  try {
    await loadMeta();
    await loadData();
  } catch (error) {
    ElMessage.error((error as Error).message);
  }
});
</script>

<style scoped>
.header-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.title {
  font-size: 22px;
  font-weight: 700;
}

.tab-row {
  margin-bottom: 12px;
}

.filter-row {
  margin-bottom: 12px;
}

.product-cell {
  display: flex;
  align-items: center;
  gap: 8px;
}

.pager-row {
  display: flex;
  justify-content: flex-end;
  margin-top: 12px;
}
</style>

// src-legacy/pages/product/SpuPage.tsx
import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import {
  Alert,
  Avatar,
  Button,
  Card,
  CardContent,
  Chip,
  MenuItem,
  Paper,
  Stack,
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableRow,
  TextField,
  Typography
} from '@mui/material';
import {
  deleteSpu,
  getBrandSimpleList,
  getCategoryList,
  getSpuCount,
  getSpuPage,
  type BrandResp,
  type CategoryResp,
  type SpuCountResp,
  type SpuResp,
  updateSpuStatus
} from '../../api/admin';
import { getProductSpuStatusLabel, PRODUCT_SPU_STATUS, PRODUCT_SPU_TAB } from '../../constants/productSpu';
import { ConfirmDialog } from '../../components/ConfirmDialog';
import { Pagination } from '../../components/Pagination';

export function SpuPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const categoryIdFromQuery = searchParams.get('categoryId') ? Number(searchParams.get('categoryId')) : '';

  const [brands, setBrands] = useState<BrandResp[]>([]);
  const [categories, setCategories] = useState<CategoryResp[]>([]);
  const [counts, setCounts] = useState<SpuCountResp | null>(null);

  const [list, setList] = useState<SpuResp[]>([]);
  const [total, setTotal] = useState(0);
  const [pageNum, setPageNum] = useState(1);
  const [pageSize, setPageSize] = useState(10);
  const [name, setName] = useState('');
  const [tabType, setTabType] = useState<number>(PRODUCT_SPU_TAB.FOR_SALE);
  const [categoryId, setCategoryId] = useState<number | ''>(categoryIdFromQuery);
  const [brandId, setBrandId] = useState<number | ''>('');
  const [errorMessage, setErrorMessage] = useState('');
  const [deleteTargetId, setDeleteTargetId] = useState<number | null>(null);

  const categoryMap = useMemo(() => new Map(categories.map((item) => [item.id, item.name])), [categories]);
  const brandMap = useMemo(() => new Map(brands.map((item) => [item.id, item.name])), [brands]);

  async function loadMeta() {
    try {
      const [brandList, categoryList, countResp] = await Promise.all([getBrandSimpleList(), getCategoryList(), getSpuCount()]);
      setBrands(brandList);
      setCategories(categoryList);
      setCounts(countResp);
    } catch (error) {
      setErrorMessage((error as Error).message);
    }
  }

  async function loadData() {
    try {
      const page = await getSpuPage(pageNum, pageSize, {
        name: name || undefined,
        tabType,
        categoryId: categoryId === '' ? undefined : categoryId,
        brandId: brandId === '' ? undefined : brandId
      });
      setList(page.list || []);
      setTotal(page.total || 0);
      setErrorMessage('');
    } catch (error) {
      setErrorMessage((error as Error).message);
    }
  }

  useEffect(() => {
    void loadMeta();
  }, []);

  useEffect(() => {
    void loadData();
  }, [pageNum, pageSize, tabType]);

  async function onDelete(id: number) {
    try {
      await deleteSpu(id);
      setDeleteTargetId(null);
      await Promise.all([loadData(), loadMeta()]);
    } catch (error) {
      setErrorMessage((error as Error).message);
    }
  }

  async function onSwitchStatus(id: number, nextStatus: number) {
    try {
      await updateSpuStatus(id, nextStatus);
      await Promise.all([loadData(), loadMeta()]);
    } catch (error) {
      setErrorMessage((error as Error).message);
    }
  }

  return (
    <Stack spacing={2}>
      <Stack direction="row" justifyContent="space-between" alignItems="center">
        <Typography variant="h4">商品 SPU</Typography>
        <Button onClick={() => navigate('/product/spu/new')}>新增</Button>
      </Stack>
      {errorMessage ? <Alert severity="error">{errorMessage}</Alert> : null}

      <Stack direction="row" spacing={1}>
        <Button
          variant={tabType === PRODUCT_SPU_TAB.FOR_SALE ? 'contained' : 'outlined'}
          onClick={() => {
            setTabType(PRODUCT_SPU_TAB.FOR_SALE);
            setPageNum(1);
          }}
        >
          出售中({counts?.enableCount ?? 0})
        </Button>
        <Button
          variant={tabType === PRODUCT_SPU_TAB.IN_WAREHOUSE ? 'contained' : 'outlined'}
          onClick={() => {
            setTabType(PRODUCT_SPU_TAB.IN_WAREHOUSE);
            setPageNum(1);
          }}
        >
          仓库中({counts?.disableCount ?? 0})
        </Button>
        <Button
          variant={tabType === PRODUCT_SPU_TAB.SOLD_OUT ? 'contained' : 'outlined'}
          onClick={() => {
            setTabType(PRODUCT_SPU_TAB.SOLD_OUT);
            setPageNum(1);
          }}
        >
          已售罄({counts?.soldOutCount ?? 0})
        </Button>
        <Button
          variant={tabType === PRODUCT_SPU_TAB.ALERT_STOCK ? 'contained' : 'outlined'}
          onClick={() => {
            setTabType(PRODUCT_SPU_TAB.ALERT_STOCK);
            setPageNum(1);
          }}
        >
          警戒库存({counts?.alertStockCount ?? 0})
        </Button>
        <Button
          variant={tabType === PRODUCT_SPU_TAB.RECYCLE_BIN ? 'contained' : 'outlined'}
          onClick={() => {
            setTabType(PRODUCT_SPU_TAB.RECYCLE_BIN);
            setPageNum(1);
          }}
        >
          回收站({counts?.recycleCount ?? 0})
        </Button>
      </Stack>

      <Card>
        <CardContent>
          <Stack direction={{ xs: 'column', md: 'row' }} spacing={1.5}>
            <TextField size="small" label="商品名称" value={name} onChange={(e) => setName(e.target.value)} />
            <TextField
              select
              size="small"
              label="分类"
              value={categoryId}
              onChange={(e) => setCategoryId(e.target.value === '' ? '' : Number(e.target.value))}
              sx={{ minWidth: 180 }}
            >
              <MenuItem value="">全部分类</MenuItem>
              {categories.map((item) => (
                <MenuItem key={item.id} value={item.id}>
                  {item.name}
                </MenuItem>
              ))}
            </TextField>
            <TextField
              select
              size="small"
              label="品牌"
              value={brandId}
              onChange={(e) => setBrandId(e.target.value === '' ? '' : Number(e.target.value))}
              sx={{ minWidth: 180 }}
            >
              <MenuItem value="">全部品牌</MenuItem>
              {brands.map((item) => (
                <MenuItem key={item.id} value={item.id}>
                  {item.name}
                </MenuItem>
              ))}
            </TextField>
            <Button onClick={() => void loadData()}>搜索</Button>
            <Button
              variant="outlined"
              onClick={() => {
                setName('');
                setCategoryId(categoryIdFromQuery);
                setBrandId('');
                setPageNum(1);
                void loadData();
              }}
            >
              重置
            </Button>
          </Stack>
        </CardContent>
      </Card>

      <Paper>
        <Table size="small">
          <TableHead>
            <TableRow>
              <TableCell>ID</TableCell>
              <TableCell>商品</TableCell>
              <TableCell>分类</TableCell>
              <TableCell>品牌</TableCell>
              <TableCell>价格</TableCell>
              <TableCell>销量</TableCell>
              <TableCell>库存</TableCell>
              <TableCell>状态</TableCell>
              <TableCell>创建时间</TableCell>
              <TableCell>操作</TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {list.length === 0 ? (
              <TableRow>
                <TableCell colSpan={10}>暂无数据</TableCell>
              </TableRow>
            ) : (
              list.map((item) => (
                <TableRow key={item.id}>
                  <TableCell>{item.id}</TableCell>
                  <TableCell>
                    <Stack direction="row" spacing={1} alignItems="center">
                      <Avatar src={item.picUrl} alt={item.name} variant="rounded" sx={{ width: 36, height: 36 }} />
                      <Typography variant="body2">{item.name}</Typography>
                    </Stack>
                  </TableCell>
                  <TableCell>{categoryMap.get(item.categoryId) || item.categoryId}</TableCell>
                  <TableCell>{brandMap.get(item.brandId) || item.brandId}</TableCell>
                  <TableCell>¥ {fenToYuan(item.price)}</TableCell>
                  <TableCell>{item.salesCount}</TableCell>
                  <TableCell>{item.stock}</TableCell>
                  <TableCell>
                    <Chip
                      size="small"
                      label={getProductSpuStatusLabel(item.status)}
                      color={item.status === PRODUCT_SPU_STATUS.ENABLE ? 'success' : item.status === PRODUCT_SPU_STATUS.RECYCLE ? 'default' : 'warning'}
                    />
                  </TableCell>
                  <TableCell>{item.createTime ? new Date(item.createTime).toLocaleString() : '-'}</TableCell>
                  <TableCell>
                    <Stack direction="row" spacing={1} flexWrap="wrap">
                      <Button size="small" variant="outlined" onClick={() => navigate(`/product/spu/${item.id}`)}>
                        详情
                      </Button>
                      <Button size="small" variant="outlined" onClick={() => navigate(`/product/spu/${item.id}/edit`)}>
                        修改
                      </Button>
                      {tabType === PRODUCT_SPU_TAB.RECYCLE_BIN ? (
                        <Button size="small" variant="outlined" onClick={() => void onSwitchStatus(item.id, PRODUCT_SPU_STATUS.DISABLE)}>
                          恢复
                        </Button>
                      ) : (
                        <Button size="small" variant="outlined" onClick={() => void onSwitchStatus(item.id, PRODUCT_SPU_STATUS.RECYCLE)}>
                          回收
                        </Button>
                      )}
                      {item.status !== PRODUCT_SPU_STATUS.RECYCLE ? (
                        <Button
                          size="small"
                          variant="outlined"
                          onClick={() =>
                            void onSwitchStatus(
                              item.id,
                              item.status === PRODUCT_SPU_STATUS.ENABLE ? PRODUCT_SPU_STATUS.DISABLE : PRODUCT_SPU_STATUS.ENABLE
                            )
                          }
                        >
                          {item.status === PRODUCT_SPU_STATUS.ENABLE ? '下架' : '上架'}
                        </Button>
                      ) : null}
                      {tabType === PRODUCT_SPU_TAB.RECYCLE_BIN ? (
                        <Button
                          size="small"
                          color="error"
                          variant="outlined"
                          onClick={() => setDeleteTargetId(item.id)}
                        >
                          删除
                        </Button>
                      ) : null}
                    </Stack>
                  </TableCell>
                </TableRow>
              ))
            )}
          </TableBody>
        </Table>
      </Paper>

      <Pagination
        pageNum={pageNum}
        pageSize={pageSize}
        total={total}
        onChange={(nextPageNum, nextPageSize) => {
          setPageNum(nextPageNum);
          setPageSize(nextPageSize);
        }}
      />

      <ConfirmDialog
        open={deleteTargetId !== null}
        title="确认删除商品"
        description={deleteTargetId === null ? '' : `确认删除 SPU #${deleteTargetId} 吗？`}
        confirmText="删除"
        onCancel={() => setDeleteTargetId(null)}
        onConfirm={() => {
          if (deleteTargetId !== null) {
            void onDelete(deleteTargetId);
          }
        }}
      />
    </Stack>
  );
}
  function fenToYuan(price?: number) {
    // 后端金额单位是分，前端列表统一展示元 / Backend uses fen; UI shows yuan
    return ((price ?? 0) / 100).toFixed(2);
  }
